from django.db import models
from django.conf import settings

class Category(models.Model):
    # category_id is automatically generated by Django as 'id'
    category_name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='categories')

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = "Categories"


class Task(models.Model):
    # STATUS and PRIORITY choices can be customized as needed
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    priority_level = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    dark_mode = models.BooleanField(default=False) # Included as it appears in the Task table in the diagram
    
    # Foreign Keys
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tasks')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='tasks')

    def __str__(self):
        return self.title


class Subtask(models.Model):
    subtask_title = models.CharField(max_length=255)
    is_completed = models.BooleanField(default=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='subtasks')

    def __str__(self):
        return self.subtask_title


class Reminder(models.Model):
    reminder_time = models.DateTimeField()
    alert_enabled = models.BooleanField(default=True)
    notification_type = models.CharField(max_length=100)
    timer_value = models.IntegerField(help_text="Timer duration in seconds/minutes", blank=True, null=True)
    countdown_value = models.IntegerField(help_text="Countdown value", blank=True, null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='reminders')

    def __str__(self):
        return f"Reminder for: {self.task.title} at {self.reminder_time}"


class Analytics(models.Model):
    period_start = models.DateTimeField()
    period_end = models.DateTimeField()
    tasks_completed = models.PositiveIntegerField(default=0)
    tasks_pending = models.PositiveIntegerField(default=0)
    completion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0.00, help_text="Percentage of completed tasks")
    
    # Foreign Keys
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='analytics')
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True, blank=True, related_name='analytics')

    def __str__(self):
        return f"Analytics for {self.user} ({self.period_start.date()} to {self.period_end.date()})"
    
    class Meta:
        verbose_name_plural = "Analytics"