from django.db import models
from django.conf import settings

class Category(models.Model): #Group tasks into categories
    # category_id is automatically generated by Django as 'id'
    category_name = models.CharField(max_length=255) #lets the user choose the categorie name
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='categories') #which category belongs to which user

    def __str__(self): #lets you see the name of the category instead of it being like category name (1)
        return self.category_name

    class Meta: #Fixes spelling instead of it being categorys it fixes it to categories.
        verbose_name_plural = "Categories"


class Task(models.Model):
    # STATUS and PRIORITY choices can be customized as needed
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    title = models.CharField(max_length=255) #Lets the user choose the title name
    description = models.TextField(blank=True, null=True) #lets the user input a description but its optional
    due_date = models.DateTimeField(blank=True, null=True)#lets the user add a due date but again optional
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')#related to STATUS_CHOICES where these are you options but by defualt its pending when left blank
    priority_level = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')#can only be low, meduim, high again if user didnt enter anything the automatically meduim
    created_at = models.DateTimeField(auto_now_add=True)#automatically saves when task is created
    updated_at = models.DateTimeField(auto_now=True)#automatically saves when task is edited
    dark_mode = models.BooleanField(default=False) # Included as it appears in the Task table in the diagram/but default light mode off
    
    # Foreign Keys
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tasks')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='tasks')

    def __str__(self):
        return self.title


class Subtask(models.Model):
    subtask_title = models.CharField(max_length=255)#lets the user choose the name of the subtask
    is_completed = models.BooleanField(default=False)#A checkbox to show when a task was completed but by default=not completed
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='subtasks')

    def __str__(self):
        return self.subtask_title


class Reminder(models.Model):#sets an alarm for a specific task
    reminder_time = models.DateTimeField()#when should the reminder go off
    alert_enabled = models.BooleanField(default=True)# its an on and off switch for the reminder which automatically turns on
    notification_type = models.CharField(max_length=100)#how to notify the user
    timer_value = models.IntegerField(help_text="Timer duration in seconds/minutes", blank=True, null=True)#how long the timer runs
    countdown_value = models.IntegerField(help_text="Countdown value", blank=True, null=True)#countdown number (optional)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='reminders')#links the class task with the class reminder and if reminder is deleted then reminder is deleted

    def __str__(self):#displays the f string message for a reminder instead of reminder object(1)
        return f"Reminder for: {self.task.title} at {self.reminder_time}"


class Analytics(models.Model):#Shows user productivity
    period_start = models.DateTimeField()#when tracking period starts
    period_end = models.DateTimeField()#when tracking period ends
    tasks_completed = models.PositiveIntegerField(default=0)#shows the completed tasks
    tasks_pending = models.PositiveIntegerField(default=0)#shows the pending tasks
    completion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0.00, help_text="Percentage of completed tasks")#percentage of completed tasks
    
    # Foreign Keys
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='analytics')#shows which anayltics belongs to which user
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True, blank=True, related_name='analytics')#links class task with class analytics and doesn't delete whole analytics if a task is deleted

    def __str__(self):#returns this f string message instead of of analytics object(1)
        return f"Analytics for {self.user} ({self.period_start.date()} to {self.period_end.date()})"
    
    class Meta:
        verbose_name_plural = "Analytics"